# Generated by Django 5.2.4 on 2025-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acumulado', models.IntegerField(verbose_name='Acumulado')),
                ('valor', models.IntegerField(verbose_name='Valor')),
            ],
        ),
    ]
